import type { Product } from "./supabase"

export type Category = "Tops" | "Cardigans" | "Dresses" | "Jeans" | "Sweaters"

export const FALLBACK_IMG = "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80"

export const FALLBACK_PRODUCTS: Omit<Product, "created_at" | "updated_at">[] = [
  {
    id: "1",
    name_en: "Floral Linen Blouse",
    name_mm: "ပန်းပွင့်ပုံ Linen ရှပ်အကျီ",
    category: "Tops",
    sizes: ["S", "M", "L"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1594938298603-c8148c4b4956?w=600&q=80",
    sold_out: false,
    sort_order: 1,
    price: 18000,
  },
  {
    id: "2",
    name_en: "Beige Knit Cardigan",
    name_mm: "Beige Knit ကာဒီဂင်",
    category: "Cardigans",
    sizes: ["S", "M", "L", "XL"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1616150638538-3dc7b7d4adf1?w=600&q=80",
    sold_out: false,
    sort_order: 2,
    price: 25000,
  },
  {
    id: "3",
    name_en: "Pastel Midi Dress",
    name_mm: "Pastel Midi ဝတ်စုံ",
    category: "Dresses",
    sizes: ["S", "M", "L"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80",
    sold_out: false,
    sort_order: 3,
    price: 28000,
  },
  {
    id: "4",
    name_en: "High Waist Jeans",
    name_mm: "High Waist ဂျင်းဘောင်းဘီ",
    category: "Jeans",
    sizes: ["28", "29", "30", "31"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
    sold_out: false,
    sort_order: 4,
    price: 22000,
  },
  {
    id: "5",
    name_en: "Ivory Knit Sweater",
    name_mm: "Ivory Knit ဆွယ်တာ",
    category: "Sweaters",
    sizes: ["S", "M", "L"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&q=80",
    sold_out: false,
    sort_order: 5,
    price: 23000,
  },
  {
    id: "6",
    name_en: "Flowy Maxi Dress",
    name_mm: "Flowy Maxi ဝတ်စုံ",
    category: "Dresses",
    sizes: ["S", "M", "L"],
    status: "In Stock",
    image_url: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80",
    sold_out: false,
    sort_order: 6,
    price: 32000,
  },
]
